In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [14]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
# Preprocess the data
df= df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [16]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [17]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [18]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(df[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [19]:
# Combine one-hot encoded columns with original data
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
# Split the data into features and target
X = df.drop('EstimatedSalary', axis=1)
y = df['EstimatedSalary']

In [21]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [23]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [25]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [27]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [28]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 14ms/step - loss: 100363.0234 - mae: 100363.0234 - val_loss: 98464.0859 - val_mae: 98464.0859
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 99428.7734 - mae: 99428.7734 - val_loss: 96586.6250 - val_mae: 96586.6250
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 96150.7188 - mae: 96150.7188 - val_loss: 91828.5938 - val_mae: 91828.5938
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - loss: 89821.3438 - mae: 89821.3438 - val_loss: 84113.1406 - val_mae: 84113.1406
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 80873.4219 - mae: 80873.4219 - val_loss: 74539.1172 - val_mae: 74539.1172
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 70982.7812 - mae: 70982.7812 - val_loss: 65305.9609 - val_mae: 65305.9609
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 62212.7109 - mae: 62212.7109 - val_loss: 57946.1406 - val_mae: 57946.1406
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 55968.1758 - mae: 55968.1758 - val_loss: 53463.9531 - val_mae: 53463.9531
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 52451.4492 - mae: 52451.4492 - val_loss: 51503.7617 - val_mae: 51503.7617
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - loss: 50964.0977 - mae: 50964.0977 - val_loss: 50836.3242 - val_mae: 50836.3242
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - loss: 50402.1367 - mae: 50402.1367 - val_loss: 50669.7070 - val_mae: 50669.7070
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 50221.5352 - mae: 50221.5352 - val_loss: 50626.0781 - val_mae: 50626.0781
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 50135.0195 - mae: 50135.0195 - val_loss: 50593.7891 - val_mae: 50593.7891
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 50069.5664 - mae: 50069.5664 - val_loss: 50573.3086 - val_mae: 50573.3086
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - loss: 50019.9609 - mae: 50019.9609 - val_loss: 50550.2969 - val_mae: 50550.2969
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 49977.0547 - mae: 49977.0547 - val_loss: 50532.3477 - val_mae: 50532.3477
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 49935.1602 - mae: 49935.1602 - val_loss: 50527.1914 - val_mae: 50527.1914
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49900.5625 - mae: 49900.5625 - val_loss: 50507.5742 - val_mae: 50507.5742
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49870.0234 - mae: 49870.0234 - val_loss: 50487.8594 - val_mae: 50487.8594
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49840.6172 - mae: 49840.6172 - val_loss: 50481.8242 - val_mae: 50481.8242
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 49816.5430 - mae: 49816.5430 - val_loss: 50474.6328 - val_mae: 50474.6328
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 46ms/step - loss: 49792.7031 - mae: 49792.7031 - val_loss: 50463.7734 - val_mae: 50463.7734
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 49769.2266 - mae: 49769.2266 - val_loss: 50453.3945 - val_mae: 50453.3945
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - loss: 49751.8828 - mae: 49751.8828 - val_loss: 50452.9688 - val_mae: 50452.9688
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 49729.9648 - mae: 49729.9648 - val_loss: 50438.8125 - val_mae: 50438.8125
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 49713.7422 - mae: 49713.7422 - val_loss: 50431.9531 - val_mae: 50431.9531
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49699.6172 - mae: 49699.6172 - val_loss: 50424.1602 - val_mae: 50424.1602
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49680.6875 - mae: 49680.6875 - val_loss: 50414.1367 - val_mae: 50414.1367
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - loss: 49667.0625 - mae: 49667.0625 - val_loss: 50401.3438 - val_mae: 50401.3438
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 49653.4648 - mae: 49653.4648 - val_loss: 50399.8359 - val_mae: 50399.8359
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 49638.4883 - mae: 49638.4883 - val_loss: 50399.3555 - val_mae: 50399.3555
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49630.8008 - mae: 49630.8008 - val_loss: 50402.1328 - val_mae: 50402.1328
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49614.7812 - mae: 49614.7812 - val_loss: 50379.3945 - val_mae: 50379.3945
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 49605.5703 - mae: 49605.5703 - val_loss: 50369.7109 - val_mae: 50369.7109
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 49595.3711 - mae: 49595.3711 - val_loss: 50368.2266 - val_mae: 50368.2266
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49584.3672 - mae: 49584.3672 - val_loss: 50374.5156 - val_mae: 50374.5156
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - loss: 49574.7969 - mae: 49574.7969 - val_loss: 50365.3086 - val_mae: 50365.3086
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49569.8516 - mae: 49569.8516 - val_loss: 50364.8789 - val_mae: 50364.8789
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 10s 21ms/step - loss: 49558.2812 - mae: 49558.2812 - val_loss: 50364.0586 - val_mae: 50364.0586
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - loss: 49547.8867 - mae: 49547.8867 - val_loss: 50353.2266 - val_mae: 50353.2266
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 49546.4062 - mae: 49546.4062 - val_loss: 50356.5000 - val_mae: 50356.5000
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - loss: 49533.1797 - mae: 49533.1797 - val_loss: 50355.5508 - val_mae: 50355.5508
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - loss: 49524.0391 - mae: 49524.0391 - val_loss: 50351.8750 - val_mae: 50351.8750
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - loss: 49515.9297 - mae: 49515.9297 - val_loss: 50353.1875 - val_mae: 50353.1875
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 49511.2656 - mae: 49511.2656 - val_loss: 50356.5430 - val_mae: 50356.5430
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - loss: 49504.4336 - mae: 49504.4336 - val_loss: 50344.4297 - val_mae: 50344.4297
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 35ms/step - loss: 49496.2734 - mae: 49496.2734 - val_loss: 50359.6914 - val_mae: 50359.6914
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 71ms/step - loss: 49493.6367 - mae: 49493.6367 - val_loss: 50351.3906 - val_mae: 50351.3906
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 33ms/step - loss: 49485.2812 - mae: 49485.2812 - val_loss: 50353.1797 - val_mae: 50353.1797
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 18ms/step - loss: 49479.4648 - mae: 49479.4648 - val_loss: 50354.7930 - val_mae: 50354.7930
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - loss: 49474.5664 - mae: 49474.5664 - val_loss: 50360.2461 - val_mae: 50360.2461
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 49469.5586 - mae: 49469.5586 - val_loss: 50344.4453 - val_mae: 50344.4453
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 21ms/step - loss: 49466.7656 - mae: 49466.7656 - val_loss: 50348.7734 - val_mae: 50348.7734
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - loss: 49458.8672 - mae: 49458.8672 - val_loss: 50356.3242 - val_mae: 50356.3242
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - loss: 49451.9805 - mae: 49451.9805 - val_loss: 50359.8633 - val_mae: 50359.8633
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49444.2930 - mae: 49444.2930 - val_loss: 50346.4805 - val_mae: 50346.4805

In [29]:
%load_ext tensorboard

In [30]:
%tensorboard --logdir regressionlogs/fit

ERROR: Timed out waiting for TensorBoard to start. It may still be running as pid 33192.

In [31]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 50344.4297 - mae: 50344.4297
Test MAE : 50344.4296875

In [32]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.